apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2020-04-27T13:22:37Z"
    generation: 2
    labels:
      run: apppy
    name: apppy
    namespace: default
    resourceVersion: "846956"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/apppy
    uid: e4cdf708-4e3b-49eb-ac35-db430360cd98
  spec:
    progressDeadlineSeconds: 600
    replicas: 10
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: apppy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: apppy
      spec:
        containers:
        - image: psvehla/py-server
          imagePullPolicy: Always
          name: apppy
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 10
    conditions:
    - lastTransitionTime: "2020-04-27T13:22:37Z"
      lastUpdateTime: "2020-04-27T13:22:41Z"
      message: ReplicaSet "apppy-76bdc866d8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-04-28T08:06:36Z"
      lastUpdateTime: "2020-04-28T08:06:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 10
    replicas: 10
    updatedReplicas: 10
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
