apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-04-28T09:42:03Z"
    generation: 2
    labels:
      run: nginx
    name: nginx
    namespace: default
    resourceVersion: "852302"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx
    uid: e2312b91-e250-4ebe-8131-0996026c9015
  spec:
    progressDeadlineSeconds: 600
    replicas: 10
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: nginx
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: nginx
      spec:
        containers:
        - image: nginx:1.15.7
          imagePullPolicy: IfNotPresent
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 10
    conditions:
    - lastTransitionTime: "2020-04-28T09:42:03Z"
      lastUpdateTime: "2020-04-28T09:42:05Z"
      message: ReplicaSet "nginx-6ffd4b789f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-04-28T09:42:11Z"
      lastUpdateTime: "2020-04-28T09:42:11Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 10
    replicas: 10
    updatedReplicas: 10
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
